"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createAssetPosition } from "@/services/assets";

export default function NewPositionPage() {
  const router = useRouter();
  const [kind, setKind] = useState<"VEHICLE" | "LOAN">("VEHICLE");
  const [name, setName] = useState(""); const [counterparty, setCounterparty] = useState(""); const [amount, setAmount] = useState(""); const [rate, setRate] = useState(""); const [confirmed, setConfirmed] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const submit = async () => { const initialMinor = Math.round(Number(amount) * 100); if (!name.trim() || !Number.isSafeInteger(initialMinor) || initialMinor <= 0 || !confirmed) return setError("Completa los datos y confirma que corresponden a una operación real."); setSaving(true); setError(""); try { const result = await createAssetPosition({ kind, name: name.trim(), counterpartyName: counterparty.trim() || undefined, initialMinor, effectiveDate: new Date().toISOString().slice(0, 10), interestModel: kind === "LOAN" && Number(rate) > 0 ? "SIMPLE_ON_OUTSTANDING_PRINCIPAL" : "NONE", rateBasisPoints: kind === "LOAN" ? Math.round(Number(rate || 0) * 100) : undefined, paymentRule: "MANUAL", idempotencyKey: `position:${crypto.randomUUID()}` }); router.push(`/assets/positions/${result.positionId}`); } catch (value: any) { setError(value?.message || "No se pudo crear la posición."); setSaving(false); } };
  const field = "rounded-xl border border-emerald-950 bg-[#07110f] px-4 py-3 text-sm outline-none focus:border-emerald-600";
  return <div className="mx-auto max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-amber-300">Alta confirmada</p><h1 className="mt-2 text-3xl font-semibold">Nueva posición</h1><p className="mt-3 text-sm leading-6 text-stone-400">Esta captura crea información financiera real. Los documentos importados nunca crearán una posición sin tu revisión.</p><section className="mt-8 space-y-5 rounded-3xl border border-emerald-950 bg-[#0b1a16] p-6 sm:p-8"><label className="grid gap-2 text-sm text-stone-400">Tipo<select value={kind} onChange={(e) => setKind(e.target.value as any)} className={field}><option value="VEHICLE">Vehículo</option><option value="LOAN">Préstamo</option></select></label><label className="grid gap-2 text-sm text-stone-400">Nombre<input value={name} onChange={(e) => setName(e.target.value)} className={field} placeholder={kind === "VEHICLE" ? "Ej. Kwid Iconic TM 2025" : "Ej. Préstamo VG"}/></label><label className="grid gap-2 text-sm text-stone-400">Contraparte (opcional)<input value={counterparty} onChange={(e) => setCounterparty(e.target.value)} className={field}/></label><label className="grid gap-2 text-sm text-stone-400">Capital inicial<input value={amount} onChange={(e) => setAmount(e.target.value)} type="number" min="0" step="0.01" className={field}/></label>{kind === "LOAN" && <label className="grid gap-2 text-sm text-stone-400">Tasa mensual (%)<input value={rate} onChange={(e) => setRate(e.target.value)} type="number" min="0" step="0.01" className={field}/></label>}<label className="flex gap-3 rounded-xl border border-amber-900/30 bg-amber-300/5 p-4 text-sm text-stone-300"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} className="mt-1 accent-emerald-400"/><span>Confirmo que estos datos representan una posición real y que revisé capital, propietario económico y fecha.</span></label>{error && <p className="text-sm text-red-300">{error}</p>}<div className="flex justify-end gap-3"><button onClick={() => router.back()} className="rounded-xl px-4 py-3 text-sm text-stone-400">Cancelar</button><button disabled={saving} onClick={() => void submit()} className="rounded-xl bg-emerald-300 px-5 py-3 text-sm font-semibold text-emerald-950 disabled:opacity-50">{saving ? "Guardando…" : "Crear posición"}</button></div></section></div>;
}
