import { httpsCallable } from "firebase/functions";
import { functions } from "@/lib/firebaseClient";

export type Agent007Observation = { id: string; caseType: string; caseId: string; intent: string; humanDecision: string; outcome: string; source?: string; sourceEvent?: string; createdAt?: any };
export type Agent007Recommendation = { id: string; kind: string; caseType: string; caseId: string; proposal: string; title?: string; explanation?: string; actionPrompt?: string | null; requiresHumanDecision?: boolean; confidence: number; status: string; resolutionReason?: string | null; resolvedByEvent?: string | null; supersededBy?: string | null; resolvedAt?: any; evidence?: Record<string, string | null>; createdAt?: any };
export type HugoScope = "GLOBAL" | "PAY0";
export type HugoProfile = "OPERATOR" | "PROGRAMMER";
export type Agent007Message = { id: string; role: "user" | "assistant"; text: string; source?: "USER" | "VERTEX_AI" | "OPENAI" | "HUGO_ENGINE" | "SYSTEM_EVENT"; scope?: HugoScope; profile?: HugoProfile; read?: boolean; relatedCaseType?: string; relatedCaseId?: string; createdAt?: any };

export async function recordAgent007Observation(input: Omit<Agent007Observation, "id" | "createdAt">) { return (await httpsCallable<typeof input, { ok: boolean; observationId: string }>(functions, "recordAgent007Observation")(input)).data; }
export async function listAgent007Observations() { return (await httpsCallable<Record<string, never>, { ok: boolean; observations: Agent007Observation[] }>(functions, "listAgent007Observations")({})).data; }
export async function listAgent007Recommendations() { return (await httpsCallable<Record<string, never>, { ok: boolean; recommendations: Agent007Recommendation[] }>(functions, "listAgent007Recommendations")({})).data; }
export async function reconcileAgent007RecommendationsNow() { return (await httpsCallable<Record<string, never>, { ok: boolean; changed: number }>(functions, "reconcileAgent007RecommendationsNow")({})).data; }
export async function resolveAgent007Recommendation(recommendationId: string, decision: "APPROVED" | "REJECTED", correction = "") { return (await httpsCallable<{ recommendationId: string; decision: string; correction?: string }, { ok: boolean }>(functions, "resolveAgent007Recommendation")({ recommendationId, decision, correction })).data; }
export async function listAgent007Messages(scope: HugoScope = "PAY0") { return (await httpsCallable<{ scope: HugoScope }, { ok: boolean; conversationId: string; messages: Agent007Message[] }>(functions, "listAgent007Messages")({ scope })).data; }
export async function markAgent007MessagesRead() { return (await httpsCallable<Record<string, never>, { ok: boolean; marked: number }>(functions, "markAgent007MessagesRead")({})).data; }
export async function sendAgent007Message(text: string, scope: HugoScope = "PAY0") { return (await httpsCallable<{ text: string; scope: HugoScope }, { ok: boolean; conversationId: string; message: Agent007Message; profile: HugoProfile; scope: HugoScope }>(functions, "sendAgent007Message")({ text, scope })).data; }
export type HugoTrace = { id: string; timestamp?: any; conversationId: string; channel: string; scope?: HugoScope; profile?: HugoProfile; task?: string; model: string; modelProvider?: string; promptVersion: string; resultStatus: string; tokenUsage?: { input?: number; output?: number; reasoning?: number }; toolsRequested?: string[]; toolsExecuted?: Array<{ tool: string; sourceSystem: string; completeness: string; latencyMs: number; result: string }>; sourceSystems?: string[]; evidenceReferences?: Array<{ sourceSystem: string; entityType: string; entityId: string; completeness: string; kind: string }>; resolvedEntities?: Array<{ sourceSystem: string; entityType: string; entityId: string; folio: string }>; memoryReferences?: Array<{ kind: string; entityType: string; entityId: string }>; memoryUsage?: { considered: number; selected: number; included: number; includedReferences: Array<{ id: string; kind: string; status: string; reason: string }> }; policyDecisions?: Array<{ policy: string; decision: string }>; latencyMs?: number; errorCode?: string | null };
export type HugoDashboard = { scope: "GLOBAL"; attention: Agent007Recommendation[]; activity: HugoTrace[]; consumption: Record<string, { requests: number; inputTokens: number; outputTokens: number; reasoningTokens: number; errors: number; averageLatencyMs: number }>;
  providers: Record<string, { status: string; model: string | null; maxOutputTokens?: number | null }>; capabilities: Array<{ id: string; system: string; risk: string; status: string }>; conversations: Array<{ id: string; scope: string; messageCount: number; lastMessage: string | null }>; systems: Array<{ id: string; status: string }> };
export async function getHugoDashboard() { return (await httpsCallable<Record<string, never>, HugoDashboard & { ok: boolean }>(functions, "getHugoDashboard")({})).data; }
export type HugoTraceFilter = { conversationId?: string; resultStatus?: string; tool?: string; sourceSystem?: string; completeness?: string; errorOnly?: boolean; from?: string; to?: string; cursor?: string; limit?: number };
export async function listAgent007Traces(filter: HugoTraceFilter = {}) { return (await httpsCallable<HugoTraceFilter, { ok: boolean; traces: HugoTrace[]; cursor: string | null; complete: boolean; scanned: number }>(functions, "listAgent007Traces")(filter)).data; }
export async function getAgent007Trace(traceId: string) { return (await httpsCallable<{ traceId: string }, { ok: boolean; trace: HugoTrace }>(functions, "getAgent007Trace")({ traceId })).data; }
export type HugoMemoryDiagnostic = { id: string; kind: string; status: string; source: string; sourceSystem: string; entityReference?: { sourceSystem: string; entityType: string; entityId: string; displayReference?: string }; confidence: number | null; createdAt: string; lastVerifiedAt: string | null; validUntil: string | null; supersededBy?: string | null; lastUsedAt?: string | null };
export async function listAgent007MemoryDiagnostics() { return (await httpsCallable<Record<string, never>, { ok: boolean; memories: HugoMemoryDiagnostic[] }>(functions, "listAgent007MemoryDiagnostics")({})).data; }
export async function createAgent007MemoryCandidate(input: { kind: "USER_STATEMENT" | "PREFERENCE" | "DECISION" | "EXPERIENCE"; content: string; entityReference?: { sourceSystem: string; entityType: string; entityId: string; displayReference?: string } }) { return (await httpsCallable<typeof input, { ok: boolean; id: string; created: boolean; status: string }>(functions, "createAgent007MemoryCandidate")(input)).data; }
export async function reviewAgent007MemoryCandidate(memoryId: string, decision: "CONFIRM" | "REJECT", supersedesId?: string) { return (await httpsCallable<{ memoryId: string; decision: string; supersedesId?: string }, { ok: boolean; changed: boolean }>(functions, "reviewAgent007MemoryCandidate")({ memoryId, decision, supersedesId })).data; }
export async function linkAgent007VerifiedExperience(observationId: string, decisionId: string, outcomeId: string) { return (await httpsCallable<{ observationId: string; decisionId: string; outcomeId: string }, { ok: boolean; id: string; created: boolean }>(functions, "linkAgent007VerifiedExperience")({ observationId, decisionId, outcomeId })).data; }
export type HugoLearningDiagnostic = { id: string; domain: string; taskType: string; state: string; revision: number; createdAt: string; provenance: string; outcome: string; feedback: string; trainingEligible: boolean; reasons: string[]; memoryId: string; traceId: string | null; correctionCode: string | null; outcomeType: string | null; supersededById?: string | null };
export type HugoLearningEvent = { eventId: string; type: string; at: string; actorUid: string | null; references: Array<{ system: string; kind: string; id: string }>; metadata: Record<string, string | number | boolean | null> };
export async function listAgent007LearningDiagnostics() { return (await httpsCallable<Record<string, never>, { ok: boolean; boundedTo: number; experiences: HugoLearningDiagnostic[] }>(functions, "listAgent007LearningDiagnostics")({})).data; }
export async function listAgent007LearningLineage(experienceId: string) { return (await httpsCallable<{ experienceId: string }, { ok: boolean; events: HugoLearningEvent[] }>(functions, "listAgent007LearningLineage")({ experienceId })).data; }
export async function supersedeAgent007LearningExperience(experienceId: string, replacementId: string) {
  return (await httpsCallable<{ experienceId: string; replacementId: string }, { ok: boolean; id: string; state: string; revision: number; supersededById: string }>(functions, "supersedeAgent007LearningExperience")({ experienceId, replacementId })).data;
}

export type HugoHumanReviewChoice = "A_BETTER" | "B_BETTER" | "EQUIVALENT" | "BOTH_ACCEPTABLE" | "BOTH_UNACCEPTABLE";
export type HugoHumanReview = { reviewId: string; evalRunId: string; caseId: string; choice: HugoHumanReviewChoice | null; reasons: string[]; note: string | null; reviewerUid: string; reviewedAt: string; revision: number; status: "REVIEWED" | "SKIPPED" };
export async function saveAgent007HumanReview(input: { evalRunId: string; caseId: string; status: "REVIEWED" | "SKIPPED"; choice?: HugoHumanReviewChoice; reasons: string[]; note?: string }) {
  return (await httpsCallable<typeof input, { ok: boolean; review: HugoHumanReview }>(functions, "saveAgent007HumanReview")(input)).data;
}
export async function listAgent007HumanReviews(evalRunId: string) {
  return (await httpsCallable<{ evalRunId: string }, { ok: boolean; reviews: HugoHumanReview[] }>(functions, "listAgent007HumanReviews")({ evalRunId })).data;
}
