import { httpsCallable } from "firebase/functions";
import { functions } from "@/lib/firebaseClient";
export type ClientItem={id:string;name:string;rfc?:string;email?:string;phone?:string;whatsapp?:string;active?:boolean;adminId?:string;rootId?:string;ownerId?:string;managedByUserId?:string;createdBy?:string;createdAt?:any;numeroCliente?:number|null;clientNumber?:number|null;iqLink?:{status?:string;clientId?:string;clientName?:string;partnerId?:string;partnerName?:string;source?:string;reviewReason?:string;candidates?:Array<{clientId?:string;clientName?:string;rfc?:string}>}|null;iqClientId?:string;iqClientName?:string};
type ClientScopePermission="view"|"operate"|"viewBasic"|"operateSolicitudes"|"operatePagos"|"operateBeneficiarios"|"operateDispersiones"|"viewBalanceInDispersion"|"requestDispersionIncidents"|"commentDispersionNotes";
type ListScopedClientsParams={uid:string;role:"superadmin"|"admin"|"operador"|string;rootId?:string;requiredPermission?:ClientScopePermission};const REFRESH_MS=30000;
function denied(e:any){const x=String(e?.code||e?.message||"").toLowerCase();return x.includes("permission-denied")}
export function listScopedClients(params:ListScopedClientsParams,cb:(items:ClientItem[])=>void,onErr?:(e:any)=>void){let cancelled=false,timer:ReturnType<typeof setTimeout>|null=null;const refresh=async()=>{try{if(!params?.uid||!params?.rootId){cb([]);return}const fn=httpsCallable(functions,"listClientsCanonical"),res:any=await fn({requiredPermission:params.requiredPermission||"view"});if(!cancelled)cb(Array.isArray(res?.data?.clients)?res.data.clients:[])}catch(e){if(!cancelled){cb([]);if(!denied(e))onErr?.(e)}}finally{if(!cancelled)timer=setTimeout(refresh,REFRESH_MS)}};void refresh();return()=>{cancelled=true;if(timer)clearTimeout(timer)}}
export async function getClientById(clientId:string,_rootId?:string):Promise<ClientItem|null>{if(!clientId)return null;const fn=httpsCallable(functions,"getClientCanonical"),res:any=await fn({clientId,requiredPermission:"view"});return res?.data?.client||null}
export function watchClientById(clientId:string,cb:(item:ClientItem|null)=>void,onErr?:(e:any)=>void){let cancelled=false,timer:ReturnType<typeof setTimeout>|null=null;const refresh=async()=>{try{const item=await getClientById(clientId);if(!cancelled)cb(item)}catch(e){if(!cancelled){cb(null);if(!denied(e))onErr?.(e)}}finally{if(!cancelled)timer=setTimeout(refresh,REFRESH_MS)}};void refresh();return()=>{cancelled=true;if(timer)clearTimeout(timer)}}
export function listClients(params:any,cb:(items:ClientItem[])=>void,onErr?:(e:any)=>void){const adminId=typeof params==="string"?params:params?.adminId;let cancelled=false,timer:ReturnType<typeof setTimeout>|null=null;const refresh=async()=>{try{if(!adminId){cb([]);return}const fn=httpsCallable(functions,"listClientsCanonical"),res:any=await fn({adminId,requiredPermission:"view"});if(!cancelled)cb(Array.isArray(res?.data?.clients)?res.data.clients:[])}catch(e){if(!cancelled){cb([]);if(!denied(e))onErr?.(e)}}finally{if(!cancelled)timer=setTimeout(refresh,REFRESH_MS)}};void refresh();return()=>{cancelled=true;if(timer)clearTimeout(timer)}}
