"use client";

import type { CSSProperties } from "react";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Plus, RefreshCw } from "lucide-react";
import { AssetsEmpty, AssetsError, AssetsLoading } from "@/components/assets/AssetsStates";
import { useAssetsOverview } from "@/components/assets/useAssetsOverview";
import { dateLabel, displayCounterpartyName, displayPositionName, effectiveAnnualRate, interestLabel, money, movementIsInflow, movementLabel, percentage } from "@/lib/assetsUi";

type Scope = "ALL" | "VEHICLE" | "LOAN";

export default function AssetsPage() {
  const { data, loading, error, reload } = useAssetsOverview();
  const [scope, setScope] = useState<Scope>("ALL");
  if (loading && !data) return <AssetsLoading/>;
  if (error && !data) return <AssetsError message={error}/>;

  const allPositions = (data?.positions || []).filter((item) => item.includedInMetrics);
  const positions = scope === "ALL" ? allPositions : allPositions.filter((item) => item.kind === scope);
  const active = positions.filter((item) => item.status === "ACTIVE");
  const positionById = new Map(positions.map((item) => [item.id, item]));
  const recent = (data?.movements || []).filter((item) => positionById.has(item.positionId)).slice(0, 6);
  const workingMinor = active.reduce((sum, position) => sum + position.snapshot.outstandingPrincipalMinor, 0);
  const recoveredMinor = positions.reduce((sum, position) => sum + position.snapshot.recoveredPrincipalMinor, 0);
  const realizedProfitMinor = positions.reduce((sum, position) => sum + position.snapshot.realizedProfitMinor, 0);
  const pendingInterestMinor = active.reduce((sum, position) => sum + position.snapshot.pendingInterestMinor, 0);
  const vehicleWorkingMinor = active.filter((position) => position.kind === "VEHICLE").reduce((sum, position) => sum + position.snapshot.outstandingPrincipalMinor, 0);
  const interestLoanMinor = active.filter((position) => position.kind === "LOAN" && Number(position.rateBasisPoints || 0) > 0).reduce((sum, position) => sum + position.snapshot.outstandingPrincipalMinor, 0);
  const noInterestLoanMinor = active.filter((position) => position.kind === "LOAN" && Number(position.rateBasisPoints || 0) === 0).reduce((sum, position) => sum + position.snapshot.outstandingPrincipalMinor, 0);
  const groups = [
    ...(scope !== "LOAN" ? [{ key: "VEHICLE" as const, label: "Vehículos", value: vehicleWorkingMinor, color: "var(--assets-accent)" }] : []),
    ...(scope !== "VEHICLE" ? [
      { key: "LOAN" as const, label: "Préstamos+INT", value: interestLoanMinor, color: "var(--assets-accent-2)" },
      { key: "LOAN" as const, label: "Préstamos", value: noInterestLoanMinor, color: "var(--assets-neutral-chart)" },
    ] : []),
    { key: "PROFIT" as const, label: "Utilidad", value: realizedProfitMinor, color: "var(--assets-positive)" },
  ];
  const max = Math.max(...groups.map((item) => item.value), 1);
  const compositionValueMinor = groups.reduce((sum, item) => sum + item.value, 0);
  const compositionTotal = Math.max(compositionValueMinor, 1);
  let angle = 0;
  const compositionGradient = `conic-gradient(${groups.map((item) => { const start = angle; angle += item.value / compositionTotal * 360; return `${item.color} ${start}deg ${angle}deg`; }).join(", ")})`;
  const investedMinor = positions.reduce((sum, position) => sum + position.snapshot.originalPrincipalMinor, 0);
  const portfolioRoi = investedMinor > 0 ? realizedProfitMinor / investedMinor : null;
  const soldVehiclePositions = positions.filter((position) => position.kind === "VEHICLE" && position.status === "LIQUIDATED");
  const soldVehiclePrincipalMinor = soldVehiclePositions.reduce((sum, position) => sum + position.snapshot.originalPrincipalMinor, 0);
  const soldVehicleProfitMinor = soldVehiclePositions.reduce((sum, position) => sum + position.snapshot.realizedProfitMinor, 0);
  const vehicleRealizedRoi = soldVehiclePrincipalMinor > 0 ? soldVehicleProfitMinor / soldVehiclePrincipalMinor : null;
  const interestLoans = active.filter((position) => position.kind === "LOAN" && Number(position.rateBasisPoints || 0) > 0);
  const interestLoanBalance = interestLoans.reduce((sum, position) => sum + position.snapshot.outstandingPrincipalMinor, 0);
  const weightedMonthlyRate = interestLoanBalance > 0 ? interestLoans.reduce((sum, position) => sum + (Number(position.rateBasisPoints || 0) / 10_000) * position.snapshot.outstandingPrincipalMinor, 0) / interestLoanBalance : null;
  const scopeLabel = scope === "VEHICLE" ? "Vehículos" : scope === "LOAN" ? "Préstamos" : "Todo el portafolio";
  const count = (kind: "VEHICLE" | "LOAN", status: string) => allPositions.filter((item) => item.kind === kind && item.status === status).length;
  const scopeButton = (value: Scope, label: string) => <button key={value} onClick={() => setScope(value)} aria-pressed={scope === value} className={`rounded-md border px-3 py-1.5 text-[11px] transition ${scope === value ? "border-[var(--assets-accent)]/45 bg-[var(--assets-accent-soft)] text-[var(--assets-accent)]" : "border-[var(--assets-border)] bg-[var(--assets-surface)] text-[var(--assets-muted)] hover:text-white"}`}>{label}</button>;

  return <div className="space-y-3">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.14em] text-[var(--assets-muted)]">Vista del Dashboard</p><div className="mt-1.5 flex flex-wrap gap-1.5">{scopeButton("ALL", "Todo")}{scopeButton("VEHICLE", "Vehículos")}{scopeButton("LOAN", "Préstamos")}</div></div><div className="flex items-center gap-2"><button onClick={() => void reload()} className="assets-control p-2 text-[var(--assets-secondary)] hover:border-[var(--assets-accent)] hover:text-white" title="Actualizar" aria-label="Actualizar"><RefreshCw size={15}/></button><Link href="/assets/positions/new" className="flex items-center gap-1.5 rounded-lg bg-[var(--assets-accent)] px-3 py-2 text-xs font-semibold text-[#17191b] transition hover:brightness-110"><Plus size={15}/>Nueva posición</Link></div></div>
    {error && <AssetsError message={error}/>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7">
      <div className="assets-panel assets-kpi p-4 sm:col-span-2"><p className="text-[10px] uppercase tracking-[0.14em] text-[var(--assets-accent)]">Capital trabajando · {scopeLabel}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{money(workingMinor)}</p><p className="mt-1 text-[10px] text-[var(--assets-muted)]">Capital vigente en posiciones activas</p></div>
      {[["Capital recuperado", recoveredMinor], ["Utilidad realizada", realizedProfitMinor], ["Interés pendiente", pendingInterestMinor]].map(([label, value], index) => <div key={String(label)} className="assets-panel assets-kpi p-4" style={{ "--assets-accent": index === 1 ? "var(--assets-positive)" : "var(--assets-accent)" } as CSSProperties}><p className="text-[10px] uppercase tracking-wide text-[var(--assets-muted)]">{label}</p><p className={`mt-2 text-base font-semibold tabular-nums ${index === 1 ? "text-[var(--assets-positive)]" : ""}`}>{money(Number(value))}</p></div>)}
      <div className="assets-panel grid grid-cols-3 divide-x divide-[var(--assets-border)] sm:col-span-2"><button onClick={() => setScope("VEHICLE")} className={`flex min-h-20 flex-col justify-between p-3 text-left transition hover:bg-white/[0.03] ${scope === "VEHICLE" ? "bg-[var(--assets-accent-soft)]" : ""}`}><p className="text-[9px] uppercase leading-4 tracking-wide text-[var(--assets-muted)]">Vehículos activos</p><p className="text-xl font-semibold tabular-nums text-[var(--assets-accent)]">{count("VEHICLE", "ACTIVE")}</p></button><button onClick={() => setScope("VEHICLE")} className={`flex min-h-20 flex-col justify-between p-3 text-left transition hover:bg-white/[0.03] ${scope === "VEHICLE" ? "bg-[var(--assets-accent-soft)]" : ""}`}><p className="text-[9px] uppercase leading-4 tracking-wide text-[var(--assets-muted)]">Vehículos vendidos</p><p className="text-xl font-semibold tabular-nums text-[var(--assets-accent)]">{count("VEHICLE", "LIQUIDATED")}</p></button><button onClick={() => setScope("LOAN")} className={`flex min-h-20 flex-col justify-between p-3 text-left transition hover:bg-white/[0.03] ${scope === "LOAN" ? "bg-[var(--assets-accent-soft)]" : ""}`}><p className="text-[9px] uppercase leading-4 tracking-wide text-[var(--assets-muted)]">Préstamos activos</p><p className="text-xl font-semibold tabular-nums text-[var(--assets-accent)]">{count("LOAN", "ACTIVE")}</p></button></div>
    </section>
    <section className={`grid gap-3 ${scope === "ALL" ? "sm:grid-cols-3" : "sm:grid-cols-2"}`}>
      {scope !== "LOAN" && <button onClick={() => setScope("VEHICLE")} className="assets-panel assets-kpi p-4 text-left transition hover:-translate-y-0.5 hover:border-[var(--assets-accent)]/60"><p className="text-[10px] uppercase tracking-[0.12em] text-[var(--assets-accent)]">Vehículos · rendimiento</p><p className="mt-2 text-2xl font-semibold tabular-nums text-[var(--assets-accent)]">{percentage(vehicleRealizedRoi)}</p><p className="mt-1 text-[11px] font-medium text-[var(--assets-secondary)]">ROI realizado en vendidos</p><p className="mt-1 text-[10px] text-[var(--assets-muted)]">{money(soldVehicleProfitMinor)} sobre {money(soldVehiclePrincipalMinor)}</p></button>}
      {scope !== "VEHICLE" && <button onClick={() => setScope("LOAN")} className="assets-panel assets-kpi p-4 text-left transition hover:-translate-y-0.5 hover:border-[var(--assets-accent)]/60"><p className="text-[10px] uppercase tracking-[0.12em] text-[var(--assets-accent)]">Préstamos · rendimiento anual</p><p className="mt-2 text-2xl font-semibold tabular-nums">{percentage(effectiveAnnualRate(weightedMonthlyRate))}</p><p className="mt-1 text-[11px] font-medium text-[var(--assets-secondary)]">{percentage(weightedMonthlyRate)} mensual ponderado</p><p className="mt-1 text-[10px] text-[var(--assets-muted)]">Equivalente efectivo compuesto</p></button>}
      <button onClick={() => setScope("ALL")} className="assets-panel assets-kpi p-4 text-left transition hover:-translate-y-0.5 hover:border-[var(--assets-accent)]/60"><p className="text-[10px] uppercase tracking-[0.12em] text-[var(--assets-muted)]">{scopeLabel} · ROI acumulado</p><p className="mt-2 text-2xl font-semibold tabular-nums text-[var(--assets-accent)]">{percentage(portfolioRoi)}</p><p className="mt-1 text-[11px] font-medium text-[var(--assets-secondary)]">Utilidad realizada sobre capital aportado</p><p className="mt-1 text-[10px] text-[var(--assets-muted)]">No mezcla recuperación con utilidad</p></button>
    </section>
    <section className="grid gap-3 xl:grid-cols-12"><div className="assets-panel xl:col-span-7"><div className="border-b border-[var(--assets-border)] px-4 py-3"><h2 className="text-sm font-semibold">Dónde está trabajando tu dinero</h2><p className="mt-0.5 text-[10px] text-[var(--assets-muted)]">{scopeLabel}; capital vigente y utilidad realizada</p></div><div className="space-y-4 p-4">{groups.map((item) => { const width = Math.max(item.value ? 3 : 0, item.value / max * 100); return <button key={item.label} onClick={() => item.key !== "PROFIT" && setScope(item.key)} className="block w-full text-left"><div className="mb-1.5 flex items-center justify-between gap-3 text-[11px]"><span className="font-medium text-[var(--assets-secondary)]">{item.label}</span><strong className={item.key === "PROFIT" ? "tabular-nums text-[var(--assets-positive)]" : "tabular-nums"}>{money(item.value)}</strong></div><div className="h-5 overflow-hidden rounded-md bg-black/25"><div className="h-full rounded-md transition-all duration-300" style={{ width: `${width}%`, backgroundColor: item.color }}/></div></button>; })}</div></div>
      <div className="assets-panel p-4 xl:col-span-5"><h2 className="text-sm font-semibold">Estado del portafolio</h2><p className="mt-1 text-[10px] text-[var(--assets-muted)]">Distribución monetaria · selecciona una categoría</p><div className="mt-4 grid items-center gap-5 sm:grid-cols-[150px_1fr]"><div className="relative mx-auto h-36 w-36 rounded-full" style={{ background: compositionGradient }}><div className="absolute inset-5 flex flex-col items-center justify-center rounded-full bg-[var(--assets-surface)]"><span className="text-[11px] font-semibold tabular-nums">{money(compositionValueMinor)}</span><span className="text-[8px] uppercase tracking-wide text-[var(--assets-muted)]">capital + utilidad</span></div></div><div className="space-y-2">{groups.map((item) => <button key={item.label} onClick={() => item.key !== "PROFIT" && setScope(item.key)} className="flex w-full items-center justify-between gap-3 border-b border-[var(--assets-border)] pb-2 text-xs last:border-0"><span className="flex items-center gap-2 text-[var(--assets-secondary)]"><i className="h-2 w-2 rounded-full" style={{ backgroundColor: item.color }}/>{item.label}</span><strong className={`tabular-nums ${item.key === "PROFIT" ? "text-[var(--assets-positive)]" : ""}`}>{money(item.value)}</strong></button>)}</div></div></div></section>
    <section className="grid gap-3 xl:grid-cols-12"><div className="assets-panel overflow-hidden xl:col-span-7"><div className="flex items-center justify-between border-b border-[var(--assets-border)] px-4 py-3"><h2 className="text-sm font-semibold">Actividad reciente · {scopeLabel}</h2><Link href="/assets/movements" className="flex items-center gap-1 text-[11px] text-[var(--assets-accent)]">Ver todos <ArrowRight size={13}/></Link></div>{recent.length ? <div className="divide-y divide-[var(--assets-border)]">{recent.map((item) => { const position = positionById.get(item.positionId)!; const inflow = movementIsInflow(item.movementType); return <div key={item.id} className="grid grid-cols-[74px_1fr_auto] items-center gap-3 px-4 py-2 text-xs"><span className="text-[10px] text-[var(--assets-muted)]">{dateLabel(item.effectiveDate || item.createdAt)}</span><span className="truncate text-[var(--assets-secondary)]">{movementLabel(item.movementType)} · {displayPositionName(position)}</span><span className={`font-medium tabular-nums ${inflow ? "text-[var(--assets-positive)]" : "text-[var(--assets-negative)]"}`}>{inflow ? "+" : "−"}{money(item.amountMinor)}</span></div>; })}</div> : <AssetsEmpty>Aún no hay actividad para este filtro.</AssetsEmpty>}</div><div className="assets-panel p-4 xl:col-span-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Posiciones relevantes · {scopeLabel}</h2><Link href="/assets/positions" className="flex items-center gap-1 text-[11px] text-[var(--assets-accent)]">Ver todas <ArrowRight size={13}/></Link></div><div className="mt-2 divide-y divide-[var(--assets-border)]">{active.slice(0, 5).map((position) => <Link href={`/assets/positions/${position.id}`} key={position.id} className="flex items-center justify-between gap-4 py-2.5 hover:text-[var(--assets-accent)]"><div className="min-w-0"><p className="truncate text-xs font-medium">{displayPositionName(position)}</p><p className="mt-0.5 text-[10px] text-[var(--assets-muted)]">{position.kind === "VEHICLE" ? displayCounterpartyName(position) : interestLabel(position)}</p></div><p className="shrink-0 text-xs font-medium tabular-nums">{money(position.snapshot.outstandingPrincipalMinor)}</p></Link>)}{!active.length && <p className="py-5 text-center text-xs text-[var(--assets-muted)]">No hay posiciones activas.</p>}</div></div></section>
    {!!data?.excludedPositionCount && <p className="text-[10px] text-[var(--assets-muted)]">{data.excludedPositionCount} {data.excludedPositionCount === 1 ? "registro está excluido" : "registros están excluidos"} de los indicadores.</p>}
  </div>;
}
