"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { accrueAssetLoanInterest, closeAssetPosition, recordAssetMovement, updateAssetPositionDetails } from "@/services/assets";
import { AssetsEmpty, AssetsError, AssetsLoading } from "@/components/assets/AssetsStates";
import { useAssetsOverview } from "@/components/assets/useAssetsOverview";
import { assetKindLabel, assetStatusLabel, dateLabel, displayCounterpartyName, displayPositionName, effectiveAnnualRate, interestLabel, isTerminalAssetPosition, money, monthlyRate, movementIsInflow, movementLabel, percentage, sourceLabel } from "@/lib/assetsUi";

export default function PositionDetailPage() {
  const { id } = useParams<{ id: string }>(); const { data, loading, error, reload } = useAssetsOverview();
  const [open, setOpen] = useState(false); const [amount, setAmount] = useState(""); const [type, setType] = useState(""); const [source, setSource] = useState("EXTERNAL_TRANSFER"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const [datesOpen, setDatesOpen] = useState(false); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState("");
  const position = data?.positions.find((item) => item.id === id); const movements = useMemo(() => (data?.movements || []).filter((item) => item.positionId === id), [data, id]);
  useEffect(() => {
    if (!position) return;
    setStartDate(position.kind === "VEHICLE" ? position.acquiredDate || "" : position.originatedDate || "");
    setEndDate(position.kind === "VEHICLE" ? position.soldDate || "" : position.interestPaymentDueDate || "");
  }, [position?.id, position?.kind, position?.acquiredDate, position?.soldDate, position?.originatedDate, position?.interestPaymentDueDate]);
  if (loading && !data) return <AssetsLoading/>; if (error && !data) return <AssetsError message={error}/>; if (!position) return <AssetsEmpty>La posición no existe o no pertenece a tu cuenta.</AssetsEmpty>;
  const terminal = isTerminalAssetPosition(position);
  const summaryCards = position.kind === "VEHICLE"
    ? [
      [terminal ? "Capital pendiente" : "Capital trabajando", position.snapshot.outstandingPrincipalMinor],
      ["Capital recuperado", position.snapshot.recoveredPrincipalMinor],
      ["Utilidad realizada", position.snapshot.realizedProfitMinor],
    ]
    : [
      ["Capital trabajando", position.snapshot.outstandingPrincipalMinor],
      ["Capital recuperado", position.snapshot.recoveredPrincipalMinor],
      ["Utilidad realizada", position.snapshot.realizedProfitMinor],
      ["Interés pendiente", position.snapshot.pendingInterestMinor],
    ];
  const choices = position.kind === "VEHICLE" ? [["VEHICLE_PRINCIPAL_RETURN", "Retorno de capital"], ["VEHICLE_PROFIT", "Utilidad"], ["VEHICLE_INVESTMENT", "Aportación adicional"]] : [["INTEREST_PAYMENT", "Pago de interés"], ["PRINCIPAL_PAYMENT", "Abono a capital"], ["INTEREST_CAPITALIZED", "Capitalizar interés"]];
  const selectedType = type || choices[0][0];
  const canClose = position.snapshot.outstandingPrincipalMinor === 0 && (position.kind === "VEHICLE" || position.snapshot.pendingInterestMinor === 0);
  const save = async () => { const amountMinor = Math.round(Number(amount) * 100); if (!Number.isSafeInteger(amountMinor) || amountMinor <= 0) return setMessage("Captura un monto válido."); setSaving(true); try { await recordAssetMovement({ positionId: id, movementType: selectedType, amountMinor, source, effectiveDate: new Date().toISOString().slice(0, 10), idempotencyKey: `movement:${crypto.randomUUID()}` }); setAmount(""); setOpen(false); setMessage("Movimiento registrado y saldos recalculados."); await reload(); } catch (value: any) { setMessage(value?.message || "No se pudo registrar el movimiento."); } finally { setSaving(false); } };
  const accrue = async () => { setSaving(true); try { const result = await accrueAssetLoanInterest({ positionId: id, periodKey: new Date().toISOString().slice(0, 7) }); setMessage(result.duplicate ? "Este periodo ya estaba procesado; no se duplicó." : result.skipped ? "Esta posición no genera interés." : `Interés registrado: ${money(result.amountMinor)}.`); await reload(); } catch (value: any) { setMessage(value?.message || "No se pudo registrar el interés."); } finally { setSaving(false); } };
  const saveDates = async () => { setSaving(true); setMessage(""); try { await updateAssetPositionDetails(position.kind === "VEHICLE" ? { positionId: id, acquiredDate: startDate || null, soldDate: endDate || null } : { positionId: id, originatedDate: startDate || null, interestPaymentDueDate: endDate || null }); setMessage("Fechas operativas actualizadas."); setDatesOpen(false); await reload(); } catch (value: any) { setMessage(value?.message || "No se pudieron actualizar las fechas."); } finally { setSaving(false); } };
  const close = async () => { const prompt = position.kind === "VEHICLE" ? "¿Confirmar liquidación de esta posición?" : "¿Confirmar que el préstamo quedó totalmente pagado?"; if (!window.confirm(prompt)) return; setSaving(true); try { await closeAssetPosition(id); setOpen(false); setMessage(position.kind === "VEHICLE" ? "Vehículo marcado como vendido." : "Préstamo pagado."); await reload(); } catch (value: any) { setMessage(value?.message || "No se pudo cerrar la posición."); } finally { setSaving(false); } };
  return <div className="space-y-4"><header className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex gap-2 text-[10px]"><span className="rounded-full bg-[var(--assets-accent-soft)] px-2 py-1 text-[var(--assets-accent)]">{assetKindLabel(position.kind)}</span><span className="rounded-full bg-white/[0.05] px-2 py-1 text-[var(--assets-secondary)]">{assetStatusLabel(position.status, position.kind)}</span></div><h1 className="mt-2 text-xl font-semibold">{displayPositionName(position)}</h1><p className="mt-1 text-xs text-[var(--assets-muted)]">{position.kind === "VEHICLE" ? displayCounterpartyName(position) : interestLabel(position)}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setDatesOpen((value) => !value)} className="assets-control px-3 py-2 text-xs text-[var(--assets-secondary)]">Editar fechas</button>{!terminal && <>{position.kind === "LOAN" && <button disabled={saving} onClick={() => void accrue()} className="assets-control px-3 py-2 text-xs text-[var(--assets-warning)]">Generar interés</button>}<button onClick={() => setOpen((value) => !value)} className="rounded-lg bg-[var(--assets-accent)] px-3 py-2 text-xs font-semibold text-[#111518]">Registrar movimiento</button><button disabled={saving || !canClose} onClick={() => void close()} title={!canClose ? (position.kind === "VEHICLE" ? "Recupera primero todo el capital." : "Liquida primero el capital y el interés pendiente.") : ""} className="assets-control px-3 py-2 text-xs text-[var(--assets-secondary)] disabled:cursor-not-allowed disabled:opacity-40">{position.kind === "VEHICLE" ? "Marcar vendido" : "Marcar pagado"}</button></>}</div></header>
    {message && <p className="rounded-lg border border-[var(--assets-border)] bg-white/[0.025] px-3 py-2 text-xs text-[var(--assets-secondary)]">{message}</p>}
    {terminal && <p className="rounded-lg border border-[var(--assets-border)] bg-white/[0.025] px-3 py-2 text-xs text-[var(--assets-secondary)]">Esta posición está {position.kind === "VEHICLE" ? "vendida" : "pagada"}. Su historial y documentos permanecen disponibles; los movimientos ordinarios están bloqueados.</p>}
    {!position.includedInMetrics && <p className="rounded-lg border border-[var(--assets-warning)]/25 bg-[var(--assets-warning)]/[0.06] px-3 py-2 text-xs text-[var(--assets-warning)]">Este registro no afecta los indicadores patrimoniales.</p>}
    <section className={`grid gap-3 sm:grid-cols-2 ${position.kind === "VEHICLE" ? "lg:grid-cols-3" : "lg:grid-cols-4"}`}>{summaryCards.map(([label, value]) => <div key={String(label)} className="assets-panel p-4"><p className="text-[10px] text-[var(--assets-muted)]">{label}</p><p className="mt-1 text-lg font-semibold tabular-nums">{money(Number(value))}</p></div>)}</section>
    <section className="grid gap-3 sm:grid-cols-3"><div className="assets-panel assets-kpi p-4"><p className="text-[10px] uppercase tracking-wide text-[var(--assets-muted)]">{position.kind === "LOAN" ? "ROI cobrado" : "ROI realizado"}</p><p className="mt-1 text-xl font-semibold tabular-nums text-[var(--assets-accent)]">{percentage(position.snapshot.roi)}</p></div>{position.kind === "LOAN" && <><div className="assets-panel assets-kpi p-4"><p className="text-[10px] uppercase tracking-wide text-[var(--assets-muted)]">Tasa mensual pactada</p><p className="mt-1 text-xl font-semibold tabular-nums">{percentage(monthlyRate(position))}</p></div><div className="assets-panel assets-kpi p-4"><p className="text-[10px] uppercase tracking-wide text-[var(--assets-muted)]">Equivalente anual</p><p className="mt-1 text-xl font-semibold tabular-nums">{percentage(effectiveAnnualRate(monthlyRate(position)))}</p><p className="mt-1 text-[10px] text-[var(--assets-muted)]">Equivalencia compuesta</p></div></>}</section>
    <section className="assets-panel p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Fechas operativas</h2><p className="mt-1 text-[10px] text-[var(--assets-muted)]">{position.kind === "VEHICLE" ? `${position.acquiredDate ? `Adquirido ${dateLabel(position.acquiredDate)}` : "Adquisición pendiente"}${position.soldDate ? ` · Vendido ${dateLabel(position.soldDate)}` : ""}` : `${position.originatedDate ? `Préstamo realizado ${dateLabel(position.originatedDate)}` : "Fecha del préstamo pendiente"}${position.interestPaymentDueDate ? ` · Cobro acordado ${dateLabel(position.interestPaymentDueDate)} (±5 días)` : " · Cobro no definido"}`}</p></div><button onClick={() => setDatesOpen((value) => !value)} className="text-[11px] text-[var(--assets-accent)]">{datesOpen ? "Cerrar" : "Editar"}</button></div>{datesOpen && <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-xs text-[var(--assets-secondary)]">{position.kind === "VEHICLE" ? "Fecha de adquisición" : "Fecha del préstamo"}<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="assets-control p-2.5"/></label><label className="grid gap-1.5 text-xs text-[var(--assets-secondary)]">{position.kind === "VEHICLE" ? "Fecha de venta" : "Próximo cobro de interés"}<input type="date" value={endDate} min={startDate || undefined} onChange={(event) => setEndDate(event.target.value)} className="assets-control p-2.5"/>{position.kind === "LOAN" && <span className="text-[10px] text-[var(--assets-muted)]">Ventana operativa automática: 5 días antes a 5 días después.</span>}</label><div className="flex justify-end gap-2 sm:col-span-2"><button onClick={() => setDatesOpen(false)} className="px-3 py-2 text-xs text-[var(--assets-muted)]">Cancelar</button><button disabled={saving} onClick={() => void saveDates()} className="rounded-lg bg-[var(--assets-accent)] px-4 py-2 text-xs font-semibold text-[#111518] disabled:opacity-50">Guardar fechas</button></div></div>}</section>
    {open && !terminal && <section className="assets-panel p-4"><h2 className="text-sm font-semibold">Nuevo movimiento</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><select value={selectedType} onChange={(event) => setType(event.target.value)} className="assets-control p-2.5 text-xs">{choices.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={source} onChange={(event) => setSource(event.target.value)} className="assets-control p-2.5 text-xs"><option value="EXTERNAL_TRANSFER">Transferencia externa</option><option value="CASH">Efectivo</option><option value="PAY0">PAY0</option><option value="MANUAL">Registro manual</option><option value="OTHER">Otro</option></select><input value={amount} onChange={(event) => setAmount(event.target.value)} type="number" min="0" step="0.01" placeholder="Monto" className="assets-control p-2.5 text-xs"/></div><div className="mt-3 flex justify-end"><button disabled={saving} onClick={() => void save()} className="rounded-lg bg-[var(--assets-accent)] px-4 py-2 text-xs font-semibold text-[#111518] disabled:opacity-50">Guardar movimiento</button></div></section>}
    <section className="assets-panel overflow-hidden"><h2 className="border-b border-[var(--assets-border)] px-4 py-3 text-sm font-semibold">Historial</h2>{movements.length ? <div className="divide-y divide-[var(--assets-border)]">{movements.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 px-4 py-2.5"><div><p className="text-xs">{movementLabel(item.movementType)}</p><p className="mt-0.5 text-[10px] text-[var(--assets-muted)]">{dateLabel(item.effectiveDate || item.createdAt)} · {sourceLabel(item.source)}</p></div><p className={`text-xs font-medium tabular-nums ${movementIsInflow(item.movementType) ? "text-[var(--assets-positive)]" : ""}`}>{movementIsInflow(item.movementType) ? "+" : "−"}{money(item.amountMinor)}</p></div>)}</div> : <AssetsEmpty>No hay movimientos.</AssetsEmpty>}</section>
  </div>;
}
