"use client";

import { useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { accrueAssetLoanInterest, recordAssetMovement } from "@/services/assets";
import { AssetsEmpty, AssetsError, AssetsLoading } from "@/components/assets/AssetsStates";
import { useAssetsOverview } from "@/components/assets/useAssetsOverview";
import { assetKindLabel, assetStatusLabel, dateLabel, displayPositionName, interestLabel, money, movementIsInflow, movementLabel, sourceLabel } from "@/lib/assetsUi";

export default function PositionDetailPage() {
  const { id } = useParams<{ id: string }>(); const { data, loading, error, reload } = useAssetsOverview();
  const [open, setOpen] = useState(false); const [amount, setAmount] = useState(""); const [type, setType] = useState(""); const [source, setSource] = useState("EXTERNAL_TRANSFER"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const position = data?.positions.find((item) => item.id === id); const movements = useMemo(() => (data?.movements || []).filter((item) => item.positionId === id), [data, id]);
  if (loading && !data) return <AssetsLoading/>; if (error && !data) return <AssetsError message={error}/>; if (!position) return <AssetsEmpty>La posición no existe o no pertenece a tu cuenta.</AssetsEmpty>;
  const choices = position.kind === "VEHICLE" ? [["VEHICLE_PRINCIPAL_RETURN", "Retorno de capital"], ["VEHICLE_PROFIT", "Utilidad"], ["VEHICLE_INVESTMENT", "Aportación adicional"]] : [["INTEREST_PAYMENT", "Pago de interés"], ["PRINCIPAL_PAYMENT", "Abono a capital"], ["INTEREST_CAPITALIZED", "Capitalizar interés"]];
  const selectedType = type || choices[0][0];
  const save = async () => { const amountMinor = Math.round(Number(amount) * 100); if (!Number.isSafeInteger(amountMinor) || amountMinor <= 0) return setMessage("Captura un monto válido."); setSaving(true); try { await recordAssetMovement({ positionId: id, movementType: selectedType, amountMinor, source, effectiveDate: new Date().toISOString().slice(0, 10), idempotencyKey: `movement:${crypto.randomUUID()}` }); setAmount(""); setOpen(false); setMessage("Movimiento registrado y saldos recalculados."); await reload(); } catch (value: any) { setMessage(value?.message || "No se pudo registrar el movimiento."); } finally { setSaving(false); } };
  const accrue = async () => { setSaving(true); try { const result = await accrueAssetLoanInterest({ positionId: id, periodKey: new Date().toISOString().slice(0, 7) }); setMessage(result.duplicate ? "Este periodo ya estaba procesado; no se duplicó." : result.skipped ? "Esta posición no genera interés." : `Interés registrado: ${money(result.amountMinor)}.`); await reload(); } catch (value: any) { setMessage(value?.message || "No se pudo registrar el interés."); } finally { setSaving(false); } };
  return <div className="space-y-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><div className="flex gap-2 text-xs"><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-emerald-200">{assetKindLabel(position.kind)}</span><span className="rounded-full bg-white/5 px-3 py-1 text-stone-400">{assetStatusLabel(position.status, position.kind)}</span></div><h1 className="mt-4 text-3xl font-semibold">{displayPositionName(position)}</h1><p className="mt-2 text-sm text-stone-500">{position.counterpartyName || interestLabel(position)}</p></div><div className="flex gap-2">{position.kind === "LOAN" && <button disabled={saving} onClick={() => void accrue()} className="rounded-xl border border-amber-800 px-4 py-3 text-sm text-amber-200">Generar interés del mes</button>}<button onClick={() => setOpen((value) => !value)} className="rounded-xl bg-emerald-300 px-4 py-3 text-sm font-semibold text-emerald-950">Registrar movimiento</button></div></header>
    {message && <p className="rounded-xl border border-emerald-900 bg-emerald-400/5 p-4 text-sm text-emerald-200">{message}</p>}
    {!position.includedInMetrics && <p className="rounded-xl border border-amber-900/50 bg-amber-400/5 p-4 text-sm text-amber-200">Registro clasificado como prueba. No afecta los indicadores patrimoniales.</p>}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Capital trabajando", position.snapshot.outstandingPrincipalMinor], ["Capital recuperado", position.snapshot.recoveredPrincipalMinor], ["Utilidad realizada", position.snapshot.realizedProfitMinor], ["Interés pendiente", position.snapshot.pendingInterestMinor]].map(([label, value]) => <div key={String(label)} className="rounded-3xl border border-emerald-950 bg-[#0b1a16] p-5"><p className="text-xs text-stone-500">{label}</p><p className="mt-3 text-xl font-semibold">{money(Number(value))}</p></div>)}</section>
    {open && <section className="rounded-3xl border border-emerald-800/50 bg-[#0b1a16] p-6"><h2 className="font-semibold">Nuevo movimiento</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><select value={selectedType} onChange={(e) => setType(e.target.value)} className="rounded-xl border border-emerald-950 bg-[#07110f] p-3 text-sm">{choices.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={source} onChange={(e) => setSource(e.target.value)} className="rounded-xl border border-emerald-950 bg-[#07110f] p-3 text-sm"><option value="EXTERNAL_TRANSFER">Transferencia externa</option><option value="CASH">Efectivo</option><option value="PAY0">PAY0</option><option value="MANUAL">Registro manual</option><option value="OTHER">Otro</option></select><input value={amount} onChange={(e) => setAmount(e.target.value)} type="number" min="0" step="0.01" placeholder="Monto" className="rounded-xl border border-emerald-950 bg-[#07110f] p-3 text-sm"/></div><div className="mt-4 flex justify-end"><button disabled={saving} onClick={() => void save()} className="rounded-xl bg-emerald-300 px-5 py-3 text-sm font-semibold text-emerald-950 disabled:opacity-50">Guardar movimiento</button></div></section>}
    <section className="rounded-3xl border border-emerald-950 bg-[#0b1a16] p-6"><h2 className="text-lg font-semibold">Historial</h2>{movements.length ? <div className="mt-4 divide-y divide-emerald-950">{movements.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm">{movementLabel(item.movementType)}</p><p className="mt-1 text-xs text-stone-500">{dateLabel(item.effectiveDate)} · {sourceLabel(item.source)}</p></div><p className={movementIsInflow(item.movementType) ? "text-emerald-300" : "text-stone-200"}>{movementIsInflow(item.movementType) ? "+" : "−"}{money(item.amountMinor)}</p></div>)}</div> : <AssetsEmpty>No hay movimientos.</AssetsEmpty>}</section>
  </div>;
}
