export type BankOption = {
  code: string;
  name: string;
  label: string;
};

export const BANK_OPTIONS: BankOption[] = [
  { code: "132", name: "ACTINVER", label: "132 - ACTINVER" },
  { code: "062", name: "AFIRME", label: "062 - AFIRME" },
  { code: "649", name: "ALBO", label: "649 - ALBO" },
  { code: "682", name: "ARCUS FI", label: "682 - ARCUS FI" },
  { code: "601", name: "ASP INTEGRA OPC", label: "601 - ASP INTEGRA OPC" },
  { code: "127", name: "AZTECA", label: "127 - AZTECA" },
  { code: "166", name: "BABIEN (BIENESTAR)", label: "166 - BABIEN (BIENESTAR)" },
  { code: "030", name: "BAJIO", label: "030 - BAJIO" },
  { code: "002", name: "BANAMEX", label: "002 - BANAMEX" },
  { code: "148", name: "BANCO COVALTO", label: "148 - BANCO COVALTO" },
  { code: "006", name: "BANCOMEXT", label: "006 - BANCOMEXT" },
  { code: "137", name: "BANCOPPEL", label: "137 - BANCOPPEL" },
  { code: "152", name: "BANCO S3", label: "152 - BANCO S3" },
  { code: "145", name: "BANCREA", label: "145 - BANCREA" },
  { code: "019", name: "BANJERCITO", label: "019 - BANJERCITO" },
  { code: "147", name: "BANKAOOL", label: "147 - BANKAOOL" },
  { code: "106", name: "BANK OF AMERICA", label: "106 - BANK OF AMERICA" },
  { code: "158", name: "BANK OF CHINA", label: "158 - BANK OF CHINA" },
  { code: "009", name: "BANOBRAS", label: "009 - BANOBRAS" },
  { code: "072", name: "BANORTE", label: "072 - BANORTE" },
  { code: "058", name: "BANREGIO", label: "058 - BANREGIO" },
  { code: "060", name: "BANSI", label: "060 - BANSI" },
  { code: "001", name: "BANXICO", label: "001 - BANXICO" },
  { code: "131", name: "GBM", label: "131 - GBM" },
  { code: "058", name: "HEY BANCO", label: "058 - HEY BANCO" },
  { code: "128", name: "HIPOTECARIA FED", label: "128 - HIPOTECARIA FED" },
  { code: "021", name: "HSBC", label: "021 - HSBC" },
  { code: "151", name: "ICBC", label: "151 - ICBC" },
  { code: "036", name: "INBURSA", label: "036 - INBURSA" },
  { code: "090", name: "INDEVAL", label: "090 - INDEVAL" },
  { code: "129", name: "INMOBILIARIO", label: "129 - INMOBILIARIO" },
  { code: "110", name: "INTERCAM BANCO", label: "110 - INTERCAM BANCO" },
  { code: "059", name: "INVEX", label: "059 - INVEX" },
  { code: "102", name: "JP MORGAN", label: "102 - JP MORGAN" },
  { code: "681", name: "KAPITAL", label: "681 - KAPITAL" },
  { code: "684", name: "KLAR", label: "684 - KLAR" },
  { code: "133", name: "KUSPIT", label: "133 - KUSPIT" },
  { code: "156", name: "LIBERTAD", label: "156 - LIBERTAD" },
  { code: "143", name: "MASARI", label: "143 - MASARI" },
  { code: "722", name: "MERCADO PAGO W", label: "722 - MERCADO PAGO W" },
  { code: "652", name: "MEXPAGO", label: "652 - MEXPAGO" },
  { code: "042", name: "MIFEL", label: "042 - MIFEL" },
  { code: "150", name: "MIZUHO BANK", label: "150 - MIZUHO BANK" },
  { code: "130", name: "MONEXCB", label: "130 - MONEXCB" },
  { code: "108", name: "MUFG (MITSUBISHI)", label: "108 - MUFG (MITSUBISHI)" },
  { code: "113", name: "MULTIVA BANCO", label: "113 - MULTIVA BANCO" },
  { code: "112", name: "BARCLAYS", label: "112 - BARCLAYS" },
  { code: "116", name: "BBASE", label: "116 - BBASE" },
  { code: "012", name: "BBVA MEXICO", label: "012 - BBVA MEXICO" },
  { code: "130", name: "BMONEX", label: "130 - BMONEX" },
  { code: "155", name: "CAJA POP MEXICA", label: "155 - CAJA POP MEXICA" },
  { code: "149", name: "CAJA TELEFONIST", label: "149 - CAJA TELEFONIST" },
  { code: "136", name: "CI BOLSA", label: "136 - CI BOLSA" },
  { code: "002", name: "CITI MEXICO", label: "002 - CITI MEXICO" },
  { code: "092", name: "CLS", label: "092 - CLS" },
  { code: "812", name: "CODI VALIDA", label: "812 - CODI VALIDA" },
  { code: "138", name: "COMPARTAMOS", label: "138 - COMPARTAMOS" },
  { code: "124", name: "CONSUBANCO", label: "124 - CONSUBANCO" },
  { code: "168", name: "COOPDESARROLLO", label: "168 - COOPDESARROLLO" },
  { code: "160", name: "CREDICAPITAL", label: "160 - CREDICAPITAL" },
  { code: "653", name: "CREDICLUB", label: "653 - CREDICLUB" },
  { code: "161", name: "CRISTOBAL COLON", label: "161 - CRISTOBAL COLON" },
  { code: "651", name: "CUENCA", label: "651 - CUENCA" },
  { code: "670", name: "DEP Y PAG DIG", label: "670 - DEP Y PAG DIG" },
  { code: "141", name: "DONDE", label: "141 - DONDE" },
  { code: "131", name: "FINAMEX", label: "131 - FINAMEX" },
  { code: "153", name: "FINCOMUN", label: "153 - FINCOMUN" },
  { code: "683", name: "FINCO PAY", label: "683 - FINCO PAY" },
  { code: "680", name: "FINTOC", label: "680 - FINTOC" },
  { code: "081", name: "FONDO (FIRA)", label: "081 - FONDO (FIRA)" },
  { code: "007", name: "NAFIN", label: "007 - NAFIN" },
  { code: "638", name: "NU MEXICO", label: "638 - NU MEXICO" },
  { code: "646", name: "NVIO", label: "646 - NVIO" },
  { code: "706", name: "PAGATODO", label: "706 - PAGATODO" },
  { code: "661", name: "PEIBO", label: "661 - PEIBO" },
  { code: "664", name: "PPBALANCEMX", label: "664 - PPBALANCEMX" },
  { code: "134", name: "PROFUTURO", label: "134 - PROFUTURO" },
  { code: "157", name: "SABADELL", label: "157 - SABADELL" },
  { code: "014", name: "SANTANDER", label: "014 - SANTANDER" },
  { code: "044", name: "SCOTIABANK", label: "044 - SCOTIABANK" },
  { code: "159", name: "SHINHAN", label: "159 - SHINHAN" },
  { code: "640", name: "BY OXXO (SPIN)", label: "640 - BY OXXO (SPIN)" },
  { code: "646", name: "STP", label: "646 - STP" },
  { code: "659", name: "SWAP", label: "659 - SWAP" },
  { code: "610", name: "TESORED", label: "610 - TESORED" },
  { code: "012", name: "TRANSFER", label: "012 - TRANSFER" },
  { code: "902", name: "TRANSFER DIRECT", label: "902 - TRANSFER DIRECT" },
  { code: "070", name: "UALA (ABC CAPITAL)", label: "070 - UALA (ABC CAPITAL)" },
  { code: "163", name: "UNAGRA", label: "163 - UNAGRA" },
  { code: "135", name: "VALMEX", label: "135 - VALMEX" },
  { code: "119", name: "VALUE", label: "119 - VALUE" },
  { code: "120", name: "VE POR MAS", label: "120 - VE POR MAS" },
  { code: "111", name: "VOLKSWAGEN", label: "111 - VOLKSWAGEN" },
  { code: "631", name: "FONDEADORA", label: "631 - FONDEADORA" },
];

export function findBankByCode(code: string) {
  return BANK_OPTIONS.find((item) => item.code === code) || null;
}
