"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ChevronDown, Plus } from "lucide-react";
import { AssetsEmpty, AssetsError, AssetsLoading } from "@/components/assets/AssetsStates";
import { useAssetsOverview } from "@/components/assets/useAssetsOverview";
import { assetStatusLabel, displayCounterpartyName, displayPositionName, effectiveAnnualRate, interestLabel, money, monthlyRate, percentage } from "@/lib/assetsUi";
import type { AssetPosition } from "@/services/assets";

function PositionCard({ position }: { position: AssetPosition }) {
  const balanceLabel = position.kind === "LOAN" ? (position.interestModel === "CAPITALIZED" ? "Saldo sujeto a interés" : "Capital pendiente") : "Capital trabajando";
  const loanMonthlyRate = monthlyRate(position);
  return <Link href={`/assets/positions/${position.id}`} className="group assets-panel block p-4 transition hover:border-[var(--assets-accent)]/60">
    <div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-sm font-semibold">{displayPositionName(position)}</h2><p className="mt-0.5 truncate text-[11px] text-[var(--assets-muted)]">{position.kind === "VEHICLE" ? displayCounterpartyName(position) : interestLabel(position)}</p></div><span className="shrink-0 rounded-full bg-[var(--assets-accent-soft)] px-2 py-1 text-[9px] text-[var(--assets-accent)]">{assetStatusLabel(position.status, position.kind)}</span></div>
    <div className="mt-3 flex items-end justify-between"><div><p className="text-[10px] text-[var(--assets-muted)]">{balanceLabel}</p><p className="mt-0.5 text-lg font-semibold tabular-nums">{money(position.snapshot.outstandingPrincipalMinor)}</p>{position.kind === "LOAN" && <p className="mt-2 text-[10px] text-[var(--assets-secondary)]">{percentage(loanMonthlyRate)} mensual · {percentage(effectiveAnnualRate(loanMonthlyRate))} anual efectivo</p>}{position.kind === "VEHICLE" && position.snapshot.realizedProfitMinor > 0 && <p className="mt-2 text-[10px] text-[var(--assets-accent)]">ROI realizado {percentage(position.snapshot.roi)}</p>}</div><ArrowRight size={14} className="text-[var(--assets-muted)] transition group-hover:translate-x-0.5"/></div>
  </Link>;
}

function HistoryTable({ positions }: { positions: AssetPosition[] }) {
  return <><div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[820px] table-fixed text-left text-xs"><thead className="border-b border-[var(--assets-border)] bg-white/[0.025] text-[10px] uppercase tracking-wider text-[var(--assets-muted)]"><tr><th className="px-3 py-2 font-medium">Posición</th><th className="w-[150px] px-3 py-2 font-medium">Contraparte</th><th className="w-[130px] px-3 py-2 text-right font-medium">Invertido</th><th className="w-[130px] px-3 py-2 text-right font-medium">Recuperado</th><th className="w-[120px] px-3 py-2 text-right font-medium">Ganancia</th><th className="w-[90px] px-3 py-2 text-right font-medium">ROI</th><th className="w-[48px] px-3 py-2"></th></tr></thead><tbody className="divide-y divide-[var(--assets-border)]">{positions.map((position) => <tr key={position.id} className="hover:bg-white/[0.025]"><td className="truncate px-3 py-2 font-medium">{displayPositionName(position)}</td><td className="truncate px-3 py-2 text-[var(--assets-muted)]">{displayCounterpartyName(position)}</td><td className="px-3 py-2 text-right tabular-nums">{money(position.snapshot.originalPrincipalMinor)}</td><td className="px-3 py-2 text-right tabular-nums">{money(position.snapshot.totalRecoveredMinor)}</td><td className="px-3 py-2 text-right font-medium tabular-nums text-[var(--assets-positive)]">+{money(position.snapshot.realizedProfitMinor)}</td><td className="px-3 py-2 text-right font-semibold tabular-nums text-[var(--assets-accent)]">{percentage(position.snapshot.roi)}</td><td className="px-3 py-2"><Link href={`/assets/positions/${position.id}`} title="Ver posición" className="text-[var(--assets-muted)] hover:text-[var(--assets-accent)]"><ArrowRight size={14}/></Link></td></tr>)}</tbody></table></div><div className="divide-y divide-[var(--assets-border)] sm:hidden">{positions.map((position) => <Link key={position.id} href={`/assets/positions/${position.id}`} className="grid grid-cols-[1fr_auto] gap-3 px-3 py-3 text-xs"><div className="min-w-0"><p className="truncate font-medium">{displayPositionName(position)}</p><p className="mt-1 text-[10px] text-[var(--assets-muted)]">{money(position.snapshot.originalPrincipalMinor)} invertido · {money(position.snapshot.realizedProfitMinor)} ganancia</p></div><span className="font-semibold tabular-nums text-[var(--assets-accent)]">ROI {percentage(position.snapshot.roi)}</span></Link>)}</div></>;
}

export default function PositionsPage() {
  const { data, loading, error } = useAssetsOverview();
  const [kind, setKind] = useState<"VEHICLE" | "LOAN">("VEHICLE");
  const [historyOpen, setHistoryOpen] = useState(false);
  if (loading && !data) return <AssetsLoading/>;
  if (error && !data) return <AssetsError message={error}/>;
  const real = (data?.positions || []).filter((item) => item.includedInMetrics && item.kind === kind);
  const active = real.filter((item) => item.status === "ACTIVE");
  const historical = real.filter((item) => item.status !== "ACTIVE");
  const excluded = (data?.positions || []).filter((item) => !item.includedInMetrics);
  const historyLabel = kind === "VEHICLE" ? "Vehículos vendidos" : "Préstamos pagados";
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-lg border border-[var(--assets-border)] bg-[var(--assets-sidebar)] p-1">{(["VEHICLE", "LOAN"] as const).map((value) => <button key={value} onClick={() => { setKind(value); setHistoryOpen(false); }} className={`rounded-md px-4 py-1.5 text-xs ${kind === value ? "bg-[var(--assets-accent-soft)] text-[var(--assets-accent)]" : "text-[var(--assets-muted)] hover:text-white"}`}>{value === "VEHICLE" ? "Vehículos" : "Préstamos"}</button>)}</div><Link href="/assets/positions/new" className="flex items-center gap-1.5 rounded-lg bg-[var(--assets-accent)] px-3 py-2 text-xs font-semibold text-[#17191b] transition hover:brightness-110"><Plus size={15}/>Nueva posición</Link></div>
    <section><div className="mb-2 flex items-center gap-2"><h1 className="text-xs font-semibold uppercase tracking-wider text-[var(--assets-secondary)]">{kind === "VEHICLE" ? "Vehículos activos" : "Préstamos activos"}</h1><span className="rounded-full bg-white/[0.05] px-2 py-0.5 text-[10px] text-[var(--assets-muted)]">{active.length}</span></div>{active.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{active.map((position) => <PositionCard key={position.id} position={position}/>)}</div> : <AssetsEmpty>{kind === "VEHICLE" ? "No hay vehículos activos." : "No hay préstamos activos."}</AssetsEmpty>}</section>
    <section className="assets-panel overflow-hidden"><button onClick={() => setHistoryOpen((value) => !value)} className="flex w-full items-center justify-between px-4 py-3 text-left"><span className="text-xs font-medium">{historyLabel} ({historical.length})</span><span className="flex items-center gap-2 text-[11px] text-[var(--assets-muted)]">{historical.length ? "Ver historial" : "Sin registros"}<ChevronDown size={14} className={`transition ${historyOpen ? "rotate-180" : ""}`}/></span></button>{historyOpen && <div className="border-t border-[var(--assets-border)]">{historical.length ? <HistoryTable positions={historical}/> : <p className="py-4 text-center text-xs text-[var(--assets-muted)]">{kind === "VEHICLE" ? "No hay vehículos vendidos todavía." : "No hay préstamos pagados todavía."}</p>}</div>}</section>
    {!!excluded.length && <details className="rounded-lg border border-[var(--assets-border)] px-4 py-3"><summary className="cursor-pointer text-[11px] text-[var(--assets-muted)]">Registros excluidos de métricas ({excluded.length})</summary><div className="mt-3 grid gap-2 sm:grid-cols-2">{excluded.map((position) => <div key={position.id} className="flex justify-between gap-3 rounded-lg bg-black/20 p-2 text-[11px] text-[var(--assets-muted)]"><span>{displayPositionName(position)}</span><span>{money(position.snapshot.outstandingPrincipalMinor)}</span></div>)}</div></details>}
  </div>;
}
