export const AUDIT_EVENTS = {
  DEPOSITO_REGISTRADO: "DEPOSITO_REGISTRADO",
  DEPOSITO_CONCILIADO: "DEPOSITO_CONCILIADO",
  DEPOSITO_RECHAZADO: "DEPOSITO_RECHAZADO",
  DISPERSION_CREADA: "DISPERSION_CREADA",
  DISPERSION_CANCELADA: "DISPERSION_CANCELADA",
  DISPERSION_DEVUELTA: "DISPERSION_DEVUELTA",
  TRASPASO_CREADO: "TRASPASO_CREADO",
  DEVOLUCION_APLICADA: "DEVOLUCION_APLICADA",
  AJUSTE_MANUAL_APLICADO: "AJUSTE_MANUAL_APLICADO",
  CORRECCION_MOVIMIENTO_APLICADA: "CORRECCION_MOVIMIENTO_APLICADA",
  TARIFA_ACTUALIZADA: "TARIFA_ACTUALIZADA",
  PISO_INVALIDO_BLOQUEADO: "PISO_INVALIDO_BLOQUEADO",
  ADELANTO_OTORGADO: "ADELANTO_OTORGADO",
  ADELANTO_LIQUIDADO: "ADELANTO_LIQUIDADO",
  ADELANTO_CANCELADO: "ADELANTO_CANCELADO",
  ADELANTO_CORREGIDO: "ADELANTO_CORREGIDO",
} as const;

export type AuditEventName = typeof AUDIT_EVENTS[keyof typeof AUDIT_EVENTS];
