"use client";

import { useEffect, useMemo, useState } from "react";
import config from "../../../evals/hugo/phase9/frozen-config.json";
import benchmark from "../../../evals/hugo/phase9/benchmark-cases.json";
import results from "../../../evals/hugo/phase9/phase9-latest-results.json";
import blind from "../../../evals/hugo/phase9/phase9-blind-review.json";

type Choice = "A_BETTER" | "B_BETTER" | "EQUIVALENT" | "BOTH_INCORRECT";
type Review = { choice: Choice; reasons: string[]; note: string; reviewedAt: string };
const choices: Array<[Choice, string]> = [["A_BETTER", "A mejor"], ["B_BETTER", "B mejor"], ["EQUIVALENT", "Equivalentes"], ["BOTH_INCORRECT", "Ambas incorrectas"]];
const reasons = ["EXACTITUD", "RAZONAMIENTO", "COMPRENSION", "CLARIDAD", "NATURALIDAD", "CONCISION", "INSTRUCCIONES", "HERRAMIENTAS", "SEGURIDAD", "ALUCINACION", "UTILIDAD"];
const card = "rounded-2xl border border-slate-800 bg-slate-900/70 p-4";

export default function HugoModelEvaluation() {
  const rows = blind.cases as Array<any>, [index, setIndex] = useState(0), [reviews, setReviews] = useState<Record<string, Review>>({}), [choice, setChoice] = useState<Choice | "">(""), [selectedReasons, setSelectedReasons] = useState<string[]>([]), [note, setNote] = useState("");
  const storageKey = `hugo-model-review-${blind.evalRunId}`;
  useEffect(() => { try { setReviews(JSON.parse(localStorage.getItem(storageKey) || "{}")); } catch { setReviews({}); } }, [storageKey]);
  const row = rows[index], saved = row ? reviews[row.caseId] : undefined;
  useEffect(() => { setChoice(saved?.choice || ""); setSelectedReasons(saved?.reasons || []); setNote(saved?.note || ""); }, [saved, row?.caseId]);
  const categoryCounts = useMemo(() => Object.entries(benchmark.cases.reduce((acc: Record<string, number>, row) => { acc[row.category] = (acc[row.category] || 0) + 1; return acc; }, {})), []);
  function save() { if (!row || !choice) return; const next = { ...reviews, [row.caseId]: { choice, reasons: selectedReasons, note, reviewedAt: new Date().toISOString() } }; setReviews(next); localStorage.setItem(storageKey, JSON.stringify(next)); }
  function download() { const blob = new Blob([JSON.stringify({ evalRunId: blind.evalRunId, reviewedAt: new Date().toISOString(), reviews }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${blind.evalRunId}-human-review.json`; link.click(); URL.revokeObjectURL(url); }
  return <main className="mx-auto max-w-[1500px] space-y-6 p-6">
    <header><p className="text-xs font-semibold uppercase tracking-[0.24em] text-violet-300">Hugo Sánchez · evaluación</p><h1 className="mt-1 text-2xl font-semibold text-white">Comparación controlada de cerebros</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Hugo conserva identidad, contexto y controles. Esta vista compara motores de inferencia bajo una configuración congelada y sin abrir HOLDOUT.</p></header>
    <section className="grid gap-4 md:grid-cols-3"><div className={card}><p className="text-xs text-slate-500">Estado</p><p className="mt-1 font-semibold text-amber-300">{results.status}</p><p className="mt-2 text-xs text-slate-400">Llamadas reales: {results.realCalls} · costo: ${results.estimatedCostUsd}</p></div><div className={card}><p className="text-xs text-slate-500">Configuración</p><p className="mt-1 text-white">{config.evalRunId}</p><p className="mt-2 text-xs text-slate-400">Prompt {config.promptVersion} · base {config.baselineCommit}</p></div><div className={card}><p className="text-xs text-slate-500">Dataset</p><p className="mt-1 text-white">{benchmark.cases.length} casos · 0 HOLDOUT</p><p className="mt-2 text-xs text-slate-400">{categoryCounts.map(([name, count]) => `${name}: ${count}`).join(" · ")}</p></div></section>
    <section className={card}><h2 className="font-semibold text-white">Métricas por proveedor</h2>{!Object.keys(results.providers).length ? <p className="mt-2 text-sm text-slate-400">Pendiente de credenciales controladas. No hay resultados que atribuir a Gemini o GPT.</p> : <div className="mt-3 grid gap-3 md:grid-cols-2">{Object.entries(results.providers).map(([provider, value]: [string, any]) => <div key={provider} className="rounded-xl bg-slate-950 p-3 text-sm"><p className="font-medium text-white">{provider} · {value.model}</p><p className="mt-2 text-slate-400">{value.calls} llamadas · {value.errors} errores · {value.inputTokens} input · {value.outputTokens} output</p><p className="text-slate-400">P50 {value.latencyP50Ms} ms · P95 {value.latencyP95Ms} ms · ${value.costUsd}</p></div>)}</div>}</section>
    <section className={card}><h2 className="font-semibold text-white">Revisión humana ciega</h2>{!row ? <p className="mt-2 text-sm text-slate-400">La interfaz está preparada. Las respuestas A/B aparecerán después de una corrida DEVELOPMENT o VALIDATION completa.</p> : <><div className="mt-3 flex items-center gap-3 text-xs"><button disabled={!index} onClick={() => setIndex(index - 1)} className="rounded bg-slate-800 px-2 py-1 disabled:opacity-40">Anterior</button><span>{index + 1}/{rows.length} · {row.category}</span><button disabled={index === rows.length - 1} onClick={() => setIndex(index + 1)} className="rounded bg-slate-800 px-2 py-1 disabled:opacity-40">Siguiente</button></div><p className="mt-3 text-white">{row.question}</p><div className="mt-3 grid gap-3 md:grid-cols-2">{[["A", row.responseA], ["B", row.responseB]].map(([label, response]) => <article key={label} className="rounded-xl bg-slate-950 p-3"><strong>Respuesta {label}</strong><p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{response || "Sin respuesta completa"}</p></article>)}</div><div className="mt-3 flex flex-wrap gap-2">{choices.map(([value, label]) => <button key={value} onClick={() => setChoice(value)} className={`rounded px-3 py-1.5 text-sm ${choice === value ? "bg-violet-600 text-white" : "bg-slate-800"}`}>{label}</button>)}</div><div className="mt-3 flex flex-wrap gap-2">{reasons.map(reason => <button key={reason} onClick={() => setSelectedReasons(current => current.includes(reason) ? current.filter(item => item !== reason) : [...current, reason])} className={`rounded px-2 py-1 text-xs ${selectedReasons.includes(reason) ? "bg-sky-800" : "bg-slate-800"}`}>{reason}</button>)}</div><textarea value={note} onChange={event => setNote(event.target.value.slice(0, 1000))} placeholder="Nota opcional" className="mt-3 w-full rounded bg-slate-950 p-2 text-sm"/><div className="mt-3 flex gap-2"><button disabled={!choice} onClick={save} className="rounded bg-violet-600 px-3 py-2 text-sm disabled:opacity-40">Guardar juicio y revelar</button><button onClick={download} className="rounded border border-slate-700 px-3 py-2 text-sm">Exportar</button></div>{saved && <p className="mt-3 text-xs text-emerald-300">Proveedor revelado después del juicio: A = {row.reveal.A}, B = {row.reveal.B}</p>}</>}</section>
  </main>;
}
