"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, X } from "lucide-react";
import { useUserProfile } from "@/lib/useUserProfile";
import { listAgent007Observations, listAgent007Recommendations, resolveAgent007Recommendation, type Agent007Observation, type Agent007Recommendation } from "@/services/agent007";
import HugoComplementInventory from "@/components/HugoComplementInventory";
import HugoTraceInspector from "@/components/HugoTraceInspector";
import HugoMemoryDiagnostics from "@/components/HugoMemoryDiagnostics";
import HugoEvalDiagnostics from "@/components/HugoEvalDiagnostics";
import HugoLearningDiagnostics from "@/components/HugoLearningDiagnostics";
import HugoPhase7Review from "@/components/HugoPhase7Review";

type Scope = "DIA" | "SEMANA" | "MES" | "ANO";
const terminal = new Set(["APPROVED", "REJECTED", "RESOLVED", "RESOLVED_BY_SYSTEM_EVENT", "SUPERSEDED", "OBSOLETE", "OBSERVATION_ONLY"]);
const d = (value: any) => { if (value?.toDate) return value.toDate(); const seconds = value?.seconds ?? value?._seconds; const parsed = typeof seconds === "number" ? new Date(seconds * 1000) : new Date(value || 0); return Number.isNaN(parsed.getTime()) ? new Date() : parsed; };
const range = (scope: Scope) => { const to = new Date(); const from = new Date(to); from.setHours(0, 0, 0, 0); if (scope === "SEMANA") from.setDate(from.getDate() - ((from.getDay() + 6) % 7)); else if (scope === "MES") from.setDate(1); else if (scope === "ANO") from.setMonth(0, 1); return { from, to }; };
const inside = (value: any, scope: Scope) => { const date = d(value); const bounds = range(scope); return date >= bounds.from && date <= bounds.to; };

function RecommendationTable({ rows, resolve }: { rows: Agent007Recommendation[]; resolve: (id: string, decision: "APPROVED" | "REJECTED") => Promise<void> }) {
  return <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-950 text-slate-500"><tr>{["Fecha", "Revisión", "Caso", "Explicación", "Confianza", "Estado", "Acciones"].map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{!rows.length && <tr><td colSpan={7} className="p-5 text-center text-slate-500">No hay registros para este periodo.</td></tr>}{rows.map((row) => <tr key={row.id} className="border-t border-slate-800"><td className="p-3 text-slate-400">{d(row.createdAt).toLocaleString("es-MX")}</td><td className="p-3 font-medium text-violet-300">{row.title || "Revisión operativa"}</td><td className="p-3 text-slate-300">{row.caseType} · {row.caseId}</td><td className="max-w-lg p-3 text-white"><p>{row.explanation || row.proposal || "Revisar"}</p>{row.actionPrompt && row.status === "PENDING_REVIEW" && <p className="mt-1 font-medium text-amber-200">{row.actionPrompt}</p>}{row.resolutionReason && row.status !== "PENDING_REVIEW" && <p className="mt-1 text-slate-500">Motivo: {row.resolutionReason}</p>}</td><td className="p-3 text-slate-400">{Math.round((row.confidence || 0) * 100)}%</td><td className="p-3">{row.status}</td><td className="p-3">{row.status === "PENDING_REVIEW" && row.requiresHumanDecision !== false ? <span className="flex gap-2"><button onClick={() => void resolve(row.id, "APPROVED")} className="rounded bg-emerald-500 p-1 text-slate-950"><Check size={14} /></button><button onClick={() => void resolve(row.id, "REJECTED")} className="rounded border border-rose-500/50 p-1 text-rose-300"><X size={14} /></button></span> : <span className="text-slate-500">Sin acción</span>}</td></tr>)}</tbody></table></div>;
}

export default function HugoPage() {
  const { profile } = useUserProfile(); const allowed = profile?.role === "superadmin";
  const [observations, setObservations] = useState<Agent007Observation[]>([]); const [recommendations, setRecommendations] = useState<Agent007Recommendation[]>([]); const [scope, setScope] = useState<Scope>("SEMANA"); const [message, setMessage] = useState("");
  const refresh = async () => { if (!allowed) return; try { const [a, b] = await Promise.all([listAgent007Observations(), listAgent007Recommendations()]); setObservations(a.observations); setRecommendations(b.recommendations); } catch (error: any) { setMessage(error?.message || "No se pudo cargar Hugo."); } };
  useEffect(() => { void refresh(); }, [allowed]);
  const scoped = useMemo(() => recommendations.filter((row) => inside(row.createdAt, scope)), [recommendations, scope]);
  const actionable = useMemo(() => scoped.filter((row) => row.status === "PENDING_REVIEW" && row.requiresHumanDecision !== false), [scoped]);
  const history = useMemo(() => scoped.filter((row) => terminal.has(row.status) || row.requiresHumanDecision === false), [scoped]);
  const memory = useMemo(() => observations.filter((row) => inside(row.createdAt, scope)), [observations, scope]);
  const resolve = async (id: string, decision: "APPROVED" | "REJECTED") => { try { await resolveAgent007Recommendation(id, decision); setMessage("Decisión guardada para Hugo."); await refresh(); } catch (error: any) { setMessage(error?.message || "No se pudo resolver la propuesta."); } };
  if (!allowed) return <main className="p-6 text-slate-400">Hugo está restringido a superadministración.</main>;
  const tabs: Scope[] = ["DIA", "SEMANA", "MES", "ANO"];
  return <main className="p-6 pb-28"><section className="rounded-2xl border border-violet-500/20 bg-slate-950 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-violet-300">AGENTE_007 · Supervisión</p><h1 className="text-3xl font-semibold text-white">Hugo entiende el estado actual</h1><p className="mt-2 text-sm text-slate-300">Separa observaciones históricas, decisiones accionables y propuestas que el propio sistema ya resolvió.</p></section><HugoComplementInventory />{message && <p className="mt-4 rounded-lg border border-sky-500/30 bg-sky-500/10 p-3 text-sm text-sky-200">{message}</p>}<div className="mt-6 flex justify-end gap-1">{tabs.map((tab) => <button key={tab} onClick={() => setScope(tab)} className={`rounded-lg px-3 py-1.5 text-xs ${scope === tab ? "bg-violet-500 text-white" : "bg-slate-800 text-slate-400"}`}>{tab}</button>)}</div><section className="mt-3 overflow-hidden rounded-2xl border border-amber-500/20 bg-slate-900"><h2 className="p-4 font-semibold text-white">Decisiones actualmente accionables</h2><RecommendationTable rows={actionable} resolve={resolve} /></section><section className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><h2 className="p-4 font-semibold text-white">Propuestas resueltas u obsoletas</h2><RecommendationTable rows={history} resolve={resolve} /></section><section className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="p-4"><h2 className="font-semibold text-white">Memoria observada</h2><p className="text-xs text-slate-500">La evidencia original se conserva aunque una propuesta deje de ser accionable.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-950 text-slate-500"><tr>{["Fecha", "Caso", "Intención", "Decisión humana", "Resultado"].map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{!memory.length && <tr><td colSpan={5} className="p-5 text-center text-slate-500">No hay memoria para este periodo.</td></tr>}{memory.map((row) => <tr key={row.id} className="border-t border-slate-800"><td className="p-3 text-slate-400">{d(row.createdAt).toLocaleString("es-MX")}</td><td className="p-3 text-violet-300">{row.caseType} · {row.caseId}</td><td className="p-3 text-white">{row.intent}</td><td className="p-3 text-slate-300">{row.humanDecision}</td><td className="p-3 text-slate-400">{row.outcome}</td></tr>)}</tbody></table></div></section><HugoTraceInspector /><HugoMemoryDiagnostics /><HugoLearningDiagnostics /><HugoEvalDiagnostics /><HugoPhase7Review /></main>;
}
